### PR TITLE
Feat/ Add arrows to show nearest trees and move to nearest feature

### LINKED ISSUE #30: Migrate the `nearest` feature from the web-map-client to core
we need to migrate the code below to the core:
https://github.com/Greenstand/treetracker-web-map-client/blob/9257c09f6d56d8a041b28e26f7eb52dbde7f33bf/src/components/App.js#L321-L340

because it is more about a pure map operation.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by pratikmdhr**
### Summary

- Migrated the `nearest` tree feature from web-map-client so that the Web-map-core displays the nearest arrows and handles the arrow click events to move to the nearest trees. 
- The map will now check for the markers every time the map is panned and display the nearest arrows if it doesn't detect any tree markers in the view. This fixes the bug that was causing the arrows not being displayed in map-client.
- A new `NearestTreeArrows` class was added for the arrows and styling code for the arrows were migrated from map-client. 
- The north arrow button will dynamically change the position depending on the next/prev `buttonPanel` #79 

closes #30 

https://user-images.githubusercontent.com/52301822/156684091-8b7e0d14-f127-4f23-a4ca-de1ba262f065.mp4

### CODE REVIEW

**Comment by pratikmdhr** [comment]
@dadiorchen  Greenstand/treetracker-web-map-client#506 needs to be merged first before this one

**Comment by dadiorchen** [comment]
@pratikmdhr fantastic job!

**Comment by dadiorchen** [comment]
@pratikmdhr I have given Amin access to you you can decide when to publish core to npm do you know how to do it

**Comment by pratikmdhr** [comment]
> @pratikmdhr I have given Amin access to you you can decide when to publish core to npm do you know how to do it

@dadiorchen thanks! yes  i think i tried it once before

**Comment by pratikmdhr** [comment]
published it!

**Pull request merged**
