### PR TITLE
chore: update types

### PR DESCRIPTION
**Pull request by RubenSmn**
# Description

- update `tsconfig` to only use `typeRoots` for package types
- fix throw Error too many arguments
- update lat lng type to use type provided by leaflet

### CODE REVIEW

**Comment by RubenSmn** [comment]
@ojafero @keyy123 could you check these changes locally. All the TypeScript errors are gone resolved but when running `npm run dev` I this error:

```js
Uncaught TypeError: events_1.default is not a constructor
```

I think it has something to do with the way the code is being converted from TS to JS but I can't find a way / don't know how to fix it

To get the changes locally you can use this.

```bash
git fetch upstream pull/151/head:update-types
git checkout update-types
```

**Comment by keyy123** [comment]
I am having issues with the first command @RubenSmn . 

image

note: I also repeated the command without 'chore/'

**Comment by RubenSmn** [comment]
@keyy123 you should use `upstream` instead of `chore/update-types`

`upstream` refers to the original Greenstand repo

**Comment by keyy123** [comment]
I have @RubenSmn. It gives me the same error:

image

**Comment by RubenSmn** [comment]
You can setup the upstream like so @keyy123 

```bash
git remote add upstream https://github.com/Greenstand/treetracker-web-map-core.git
```


https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork

**Pull request merged**
