### PR TITLE
Fix/ci-tests

### PR DESCRIPTION
**Pull request by keyy123**
Fixes issue #149.

The reason this PR is important is it prevents our test suite from failing which allows our CI/CD to pass all tests confirming that web-map-core does what we expect it to do. 

[X]It is thoroughly tested (Jest, Cypress).
[X] Previous test suites and code do not throw new errors/warnings
[X] This is a bug fix that does not add any new features.

note: The template is not here in web-map-core for some reason...

### CODE REVIEW

**Review by RubenSmn — CHANGES_REQUESTED** [review]

**Review by RubenSmn — APPROVED** [review]
Thanks!

**Comment by dadiorchen** [comment]
@keyy123 can you help solve the conflicts? We need to merge this PR, there are falures in the CIs

**Comment by keyy123** [comment]
On it @dadiorchen

**Comment by dadiorchen** [comment]
@keyy123 awsome!

**Pull request merged**
